<?php

def('LIMNY_ADMINISTRATION', 'Limny administration');
def('USERNAME', 'Username');
def('PASSWORD', 'Password');
def('REMEMBER_ME', 'Remember me');
def('SIGN_IN', 'Sign in');
def('DASHBOARD', 'Dashboard');
def('UPDATE', 'Update');
def('VISIBILITY', 'Visibility');
def('BLOCKS', 'Blocks');
def('WIDGETS', 'Widgets');
def('THEMES', 'Themes');
def('USERS', 'Users');
def('ROLES', 'Roles');
def('APPLICATIONS', 'Applications');
def('CONFIGURATION', 'Configuration');
def('TITLE', 'Title');
def('MOTTO', 'Motto');
def('DESCRIPTION', 'Description');
def('HEADER', 'Header');
def('FOOTER', 'Footer');
def('CACHE_LIFETIME', 'Cache Lifetime');
def('DEFAULT_CONTENT', 'Default Content');
def('APPLICATION', 'Application');
def('QUERY', 'Query');
def('TEXT', 'Text');
def('LANGUAGE', 'Language');
def('UNINSTALLED', 'Uninstalled');
def('INSTALL', 'Install');
def('INSTALLED', 'Installed');
def('UNINSTALL', 'Uninstall');
def('YES', 'Yes');
def('NO', 'No');
def('DEPENDS_ON', 'Depends on');
def('REQUIRED_BY', 'Required by');
def('NOT_COMPATIBLE', 'Not compatible');
def('BY', 'by');
def('SET_AS_DEFAULT', 'Set as default');
def('EDIT', 'Edit');
def('ERROR', 'Error');
def('SAVE_CHANGES', 'Save changes');
def('SAVING', 'Saving');
def('PREVIEW', 'Preview');
def('TIME_ZONE', 'Time Zone');
def('CURRENT_DATE_TIME', 'Current date/time');
def('FILE', 'File');
def('INSTALL_NEW', 'Install new');
def('EMAIL', 'Email');
def('STATUS', 'Status');
def('LAST_ACTIVITY', 'Last activity');
def('NEVER', 'Never');
def('SECOND', 'second');
def('MINUTE', 'minute');
def('HOUR', 'hour');
def('DAY', 'day');
def('WEEK', 'week');
def('MONTH', 'month');
def('YEAR', 'year');
def('DECADE', 'decade');
def('PLURAL_S', 's');
def('AGO', 'ago');
def('ENABLE', 'Enable');
def('DISABLE', 'Disable');
def('_DEFAULT_', 'Default');
def('ID', 'ID');
def('THEME', 'Theme');
def('LAST_IP', 'Last IP');
def('LAST_LOGIN', 'Last login');
def('NAME', 'Name');
def('PERMISSIONS', 'Permissions');
def('ADMIN', 'Admin');
def('APP', 'App');
def('SIGN_OUT', 'Sign out');
def('PROFILE', 'Profile');
def('NICK_NAME', 'Nick name');
def('FIRST_NAME', 'First name');
def('LAST_NAME', 'Last name');
def('NEW_PASSWORD', 'New password');
def('REPEAT_NEW_PASSWORD', 'Repeat new password');
def('MENU', 'Menu');
def('TOOLTIP', 'Tooltip');
def('ADDRESS', 'Address');
def('NEW_WINDOW', 'New window');
def('ORDER', 'Order');
def('CALENDAR', 'Calendar');
def('GREGORIAN', 'Gregorian');
def('SOLAR_HIJRI', 'Solar Hijri');
def('DATE_FORMAT', 'Date Format');
def('USER_REGISTRATION', 'User Registration');
def('URL_MODE', 'URL Mode');
def('SIMPLE', 'Simple');
def('STANDARD', 'Standard');
def('EMAIL_CONFIRMATION', 'Email Confirmation');
def('SORT', 'Sort');
def('NOTIFICATIONS', 'Notifications');
def('UNSIGNED', 'Unsigned');
def('CHANGE', 'Change');
def('SMTP_HOST', 'SMTP Host');
def('SMTP_PORT', 'SMTP Port');
def('SMTP_SECURITY', 'SMTP Security');
def('SMTP_AUTHENTICATION', 'SMTP Authentication');
def('YES', 'Yes');
def('NO', 'No');
def('SMTP_USERNAME', 'SMTP Username');
def('SMTP_PASSWORD', 'SMTP Password');
def('SECURITY_CODE', 'Security code');

def('SENTENCE_1', 'Please enter your username');
def('SENTENCE_2', 'Please enter your password');
def('SENTENCE_3', 'Invalid username or password');
def('SENTENCE_4', 'Maximum lifetime for cached pages');
def('SENTENCE_5', 'Configuration updated successfully.');
def('SENTENCE_6', 'There are no app installed.');
def('SENTENCE_7', 'All data will be lost, are you sure?');
def('SENTENCE_8', 'No theme found.');
def('SENTENCE_9', 'Theme not found.');
def('SENTENCE_10', 'No changes have been made.');
def('SENTENCE_11', 'Error in saving changes.');
def('SENTENCE_12', 'Saved successfully.');
def('SENTENCE_13', 'There are no widget installed.');
def('SENTENCE_14', 'Only compressed widget file (.zip)');
def('SENTENCE_15', 'Zip archive only is allowed.');
def('SENTENCE_16', 'Widget will be removed, are you sure?');
def('SENTENCE_17', 'Cannot open the zip archive.');
def('SENTENCE_18', 'Zip archive is empty.');
def('SENTENCE_19', 'Widget files not found in the archive.');
def('SENTENCE_20', 'This username is already taken.');
def('SENTENCE_21', 'Leave it blank if don\'t want to change.');
def('SENTENCE_22', 'Username must contain 3 characters at least.');
def('SENTENCE_23', 'Username can only contain alphanumeric characters.');
def('SENTENCE_24', 'Password must contain 6 characters at least.');
def('SENTENCE_25', 'This email address is already in use.');
def('SENTENCE_26', 'The email address is not valid.');
def('SENTENCE_27', 'Profile updated successfully.');
def('SENTENCE_28', 'New passwords are not the same.');
def('SENTENCE_29', 'The password is not correct.');
def('SENTENCE_30', 'PHP Date Format: http://php.net/manual/en/function.date.php');
def('SENTENCE_31', 'This page does not exists or your account does not have enough permission to access this page.');
def('SENTENCE_32', 'Page not found or app is not installed.');
def('SENTENCE_33', 'Application page not found.');
def('SENTENCE_34', 'There is no notification.');
def('SENTENCE_35', 'This option is disabled by security');
def('SENTENCE_36', 'Write app name or page inside [] for link to internal pages.');
def('SENTENCE_37', 'The entry security code is incorrect.');

?>